### PR TITLE
Updates for UE4.25

### PR DESCRIPTION
**Pull request by VonHirsch**
Minor API Updates for Unreal Engine Version 4.25

### CODE REVIEW

**Comment by strangergwenn** [comment]
Thank you for authoring the first Helium Rain commit in years ;)

**Comment by VonHirsch** [comment]
Honored!  Helium Rain is one of the most professional UE open source (MIT licensed ofc) code bases I've run across.  The code is immaculate.

Now that I know you're accepting PR's i'm going to submit another very small update to this one because I put the wrong decompression type (I didn't realize that save-game compress is Gzip and uncompress is Zlib)

**Comment by VonHirsch** [comment]
Do you want me to submit this other small PR?  or do you want to back this one out and I re-submit a corrected one?  Either way i'm good.

**Comment by strangergwenn** [comment]
Feel free to push a new fix PR. Do note that I won't be testing your changes - I probably should move this stuff to a branch but an UE version update is fine by me. Just make sure it works !

**Comment by VonHirsch** [comment]
ok no problem, totally agree.  If I think I'll be committing anything "new" I'll check ping you first somehow

**Pull request merged**
